[package]
name = "anti-dbg-macros"
version = "0.1.0"
edition = "2024"
description = "anti-dbg 的过程宏实现：函数级检测注入属性宏"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ZEROLINGG/anti-dbg"


[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = ["full", "derive", "visit-mut"] }
quote = "1.0"
proc-macro2 = "1.0"


lib-unknown = { version = "0.1", default-features = false, features = ["rand", "rand-expand"]}
